# Generated by Django 3.2.5 on 2021-07-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='赛事id')),
                ('name', models.CharField(max_length=255, verbose_name='赛事名称')),
                ('type', models.CharField(max_length=255, verbose_name='赛事类型')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], verbose_name='性别')),
                ('unit', models.CharField(max_length=255, verbose_name='成绩单位')),
                ('data', models.CharField(max_length=255, verbose_name='信息')),
                ('status', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], verbose_name='性别')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '赛事表',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学院id')),
                ('name', models.CharField(max_length=255, verbose_name='学院名称')),
                ('data', models.CharField(max_length=255, verbose_name='学院信息')),
            ],
            options={
                'verbose_name_plural': '学院表',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运动员id')),
                ('username', models.CharField(max_length=7, verbose_name='学号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], verbose_name='性别')),
                ('data', models.CharField(max_length=255, null=True, verbose_name='数据 ')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.institution')),
            ],
            options={
                'verbose_name_plural': '运动员表',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='成绩表id')),
                ('score', models.FloatField(max_length=255, null=True, verbose_name='成绩')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.player')),
            ],
            options={
                'verbose_name_plural': '成绩表',
            },
        ),
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='报名表id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.player')),
            ],
            options={
                'verbose_name_plural': '报名表',
            },
        ),
    ]
