# Generated by Django 3.2.5 on 2021-07-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255, verbose_name='联系方式')),
                ('content', models.CharField(max_length=255, verbose_name='投诉内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '投诉表',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.CharField(max_length=255, verbose_name='内容(Markdown)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '新闻表',
            },
        ),
        migrations.AlterField(
            model_name='enroll',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.game', verbose_name='比赛'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.player', verbose_name='运动员'),
        ),
        migrations.AlterField(
            model_name='game',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '检录'), (2, '结束')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='学院信息'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数据 '),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.institution', verbose_name='学院名'),
        ),
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.game', verbose_name='比赛'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportmeeting.player', verbose_name='运动员'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(null=True, verbose_name='成绩'),
        ),
    ]
