# Generated by Django 3.2.5 on 2021-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0002_auto_20210718_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
