# Generated by Django 3.2.5 on 2021-07-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0003_alter_game_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='finall_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='决赛', to='sportmeeting.game', verbose_name='决赛'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='finall_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='决赛成绩', to='sportmeeting.score', verbose_name='决赛成绩'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='初赛成绩', to='sportmeeting.score', verbose_name='初赛成绩'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.IntegerField(choices=[(1, '初赛'), (2, '决赛')], default=1, verbose_name='初预赛'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='初赛', to='sportmeeting.game', verbose_name='初赛'),
        ),
    ]
