# Generated by Django 3.2.5 on 2021-07-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0004_auto_20210720_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='finall_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='决赛', to='sportmeeting.game', verbose_name='决赛'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='finall_score',
            field=models.FloatField(null=True, verbose_name='初赛成绩'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='score',
            field=models.FloatField(null=True, verbose_name='初赛成绩'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
