# Generated by Django 3.2.5 on 2021-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0005_auto_20210720_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='finall_score',
            field=models.FloatField(blank=True, null=True, verbose_name='决赛成绩'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='初赛成绩'),
        ),
    ]
