# Generated by Django 3.2.5 on 2021-08-02 05:42

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportmeeting', '0006_auto_20210802_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
