"""
Django settings for sport project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-su2zn1cwz1n(632-md!n@exaq++c8^=__vnv5tl++pua3kv%%1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'mdeditor',
    # 'stdimage',  # 上传图片
    'import_export',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sportmeeting.apps.SportmeetingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sport.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sport.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 默认
        'NAME': 'sport',  # 连接的数据库
        'HOST': '42.193.126.125',  # mysql的ip地址
        'PORT': 3306,  # mysql的端口
        'USER': 'sport',  # mysql的用户名
        'PASSWORD': 'sport',  # mysql的密码
        # 'OPTIONS': {
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        #     'charset': 'utf8mb4'
        # }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# SimpleUI配置

# SIMPLEUI_LOGO = 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.mp.sohu.com%2Fupload
# %2F20170515%2Fd4a216eaf32e4c0b9255d329ee3ed677_th.png&refer=http%3A%2F%2Fimg.mp.sohu.com&app=2002&size=f9999,
# 10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1629274896&t=ff49ad82b6541366f49602e95baecdec'

SIMPLEUI_ANALYSIS = True  # 使用分析
SIMPLEUI_HOME_INFO = False  # 服务器信息

import time

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['前台首页', '赛事管理', '宣传管理', '权限认证', '系统设置'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'name': '前台首页',
            'icon': 'fas fa-rocket',
            'url': 'http://localhost:8080/'
        },
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '管理员账号',
                    'icon': 'fas fa-users',
                    'url': 'auth/user/'
                },
                {
                    'name': '权限组',
                    'icon': 'fas fa-users-cog',
                    'url': 'auth/group/'
                }

            ]
        },
        {
            'app': 'sportmeeting',
            'name': '赛事管理',
            'icon': 'fas fa-running',
            'models': [
                {
                    'name': '运动员管理',
                    'icon': 'far fa-id-card',
                    'url': 'sportmeeting/player/'
                },
                {
                    'name': '比赛管理',
                    'icon': 'fas fa-basketball-ball',
                    'url': 'sportmeeting/game/'
                },
                {
                    'name': '报名信息',
                    'icon': 'fas fa-table',
                    'url': 'sportmeeting/enroll/'
                },
                {
                    'name': '成绩管理',
                    'icon': 'fas fa-sticky-note',
                    'url': 'sportmeeting/score/'
                },

            ]
        },
        {
            'name': '系统设置',
            'icon': 'fas fa-tools',
            'models': [
                {
                    'name': '网站设置',
                    'url': 'https://baidu.com',
                    'icon': 'fas fa-cogs'
                },
                {
                    'name': '学院管理',
                    'url': 'sportmeeting/institution/',
                    'icon': 'fas fa-university'
                },

            ]
        },
        {
            'name': '宣传管理',
            'icon': 'fas fa-bullhorn',
            'models': [
                {
                    'name': '投诉信息',
                    'url': 'sportmeeting/complaint/',
                    'icon': 'fas fa-frown'
                },
                {
                    'name': '新闻管理',
                    'url': 'sportmeeting/news/',
                    'icon': 'far fa-newspaper'
                },

            ]
        }
    ]
}
